// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1MjOue8DWmDx7RByflY9G2PWrlGoRAUo',
    appId: '1:1054462077721:web:f87a744e846b32b899f388',
    messagingSenderId: '1054462077721',
    projectId: 'school-project-c69e6',
    authDomain: 'school-project-c69e6.firebaseapp.com',
    storageBucket: 'school-project-c69e6.firebasestorage.app',
    measurementId: 'G-WLECTQ26T9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmFrl1cxH6f4YXe0RZZ7GMOZzUKPdDeRI',
    appId: '1:1054462077721:android:34dbe1413fabf50d99f388',
    messagingSenderId: '1054462077721',
    projectId: 'school-project-c69e6',
    storageBucket: 'school-project-c69e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcL6EMzB6ObhjQo1e1hNLVhXP8ZvUa-dQ',
    appId: '1:1054462077721:ios:a3a5a99eb8e2855b99f388',
    messagingSenderId: '1054462077721',
    projectId: 'school-project-c69e6',
    storageBucket: 'school-project-c69e6.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcL6EMzB6ObhjQo1e1hNLVhXP8ZvUa-dQ',
    appId: '1:1054462077721:ios:a3a5a99eb8e2855b99f388',
    messagingSenderId: '1054462077721',
    projectId: 'school-project-c69e6',
    storageBucket: 'school-project-c69e6.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1MjOue8DWmDx7RByflY9G2PWrlGoRAUo',
    appId: '1:1054462077721:web:f552a7d9989991d699f388',
    messagingSenderId: '1054462077721',
    projectId: 'school-project-c69e6',
    authDomain: 'school-project-c69e6.firebaseapp.com',
    storageBucket: 'school-project-c69e6.firebasestorage.app',
    measurementId: 'G-QNZHYZKHNK',
  );
}
